### ISSUE TITLE
Settings - error when updating password and passwords are visible

### ISSUE THREAD

**Issue by adcarnec** [JuanBraco/ft_transcendance#53]

**Comment by adcarnec** [comment]
currentpassword coucou
ENTER UPDATE PASSWORD
New password { newPassword: '123456' }
error changing password TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at new NodeError (node:internal/errors:387:5)
    at Function.from (node:buffer:328:9)
    at Object.hash (/goinfre/adcarnec/ft_transcendance/backend/node_modules/argon2/argon2.js:58:42)
    at UserController.updatePassword (/goinfre/adcarnec/ft_transcendance/backend/src/user/user.controller.ts:372:25)
    at /goinfre/adcarnec/ft_transcendance/backend/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /goinfre/adcarnec/ft_transcendance/backend/node_modules/@nestjs/core/router/router-proxy.js:9:17 {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by lmelard** [comment]
error when updating password : OK 
passwords are visible: WIP

**Comment by lmelard** [comment]
OK
